### ISSUE TITLE
[1.14.4] Fails to load on dedicated server

### ISSUE THREAD

**Issue by noobanidus** [jglrxavpok/Entity-Spring#9]
Sorry for the lack of information, this is all I have left as I've been having to prune multiple mods:

```
    Entity Spring (entityspring) has failed to load correctly
§7Attempted to load class org/jglrxavpok/spring/client/ClientEventSink for invalid dist DEDICATED_SERVER,
```

**Comment by jglrxavpok** [comment]
I sadly cannot reproduce the issue with Entity-Spring by itself.
I attempted a fix nonetheless in 9dd270762f7f1c843a477c2673a570e713300623
It will be available in 4.0.1

**Comment by noobanidus** [comment]
That's fine! Just from looking at it, it should resolve the issue of your client events class potentially trying to classload things that don't exist on the server. I'm just sorry I couldn't give you more information, as I was in a bit of a mad, late-night dash to update a server before I went to bed. Thanks for looking into it!

**Comment by NielsPilgaard** [comment]
4.0.1 did not resolve the issue.
https://gist.github.com/NillerMedDild/6f4482eb1eb29b5aa44f8da43f40da86
